### ISSUE TITLE
give some up-to-date var examples

### ISSUE THREAD

**Issue by zerwes** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense#14]

**Comment by Jonybat** [comment]
This seems to be more relevant now, as https://github.com/naturalis/oss-network-demo/tree/master/ansible/basic does not seem to be available anymore

**Comment by TobiasMuellerES** [comment]
Is there any chance to get a current set of example variables? We're currently adapting the role to deploy multiple OPNsense Instances for a customer.

Currently i'm rewriting the tasks wie need to use dictionary structures like the one already used for wireguard. I would like to maintain the same feature set and not only the features we're currently using, but for example in the [interfaces](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense/blob/main/tasks/interfaces.yml) tasks i don't understand why there're so many task. from my point of view it seems that most of the `interfaces - *` jobs can be merged in a one or two task.

When i'm done, i can upload our role to github and you can try to migrate some of the changes to the current role if you like.
Problem is that due to the changes in the variables from a list with key/values to a dictionary, there's no backwards compatibility. You've to rewrite all your variables if you would like to use the new system.

**Comment by zerwes** [comment]
Hello @TobiasMuellerES 
Nice to hear you found this branch of the playbook ...

> Is there any chance to get a current set of example variables?

I added some examples in ec496d9

> in the interfaces tasks i don't understand why there're so many task

Well, you are right ... at least the remove interface task is now deprecated and will be removed in favor of the generic `opn_unset` (39ecb3d)
Regarding the other tasks ... well, maybe with some jinja2 voodoo one or two of them can be consolidated, but this is not my primary focus, especially as the readability will suffer.
I have some devices here managed by the role with up to 50 interface definitions and I never had the impression that the number of the interface tasks slows down the playbook execution significantly.

> Currently i'm rewriting the tasks we need to use dictionary structures like the one already used for wireguard.

Well, the key/value structure is not my favorite too, but this is the original state of the role. Breaking backward compatibility is no option for me! Using dicts strukture for new tasks is fine (that is what I did with the wireguard vars) but for already existing tasks and vars I will try to keep the old structure or at least provide some way to convert the old vars.

In fact we do not use the key/value syntax directly. Most of our var definitions have our own structure (using dicts!), as it is the base for all our network tasks not only targeting the opnsense devices. And from these base definitions we use some tasks with jinja2 templates to generate the opnsense vars in the desired format (see naturalis/ansible-opnsense#61 for a example). Maybe this might be a option for you too instead of rewriting the tasks and breaking backward compatibility.

If I can provide some more information, just let me know.
Greetings

**Comment by TobiasMuellerES** [comment]
Hi @zerwes,

thanks for your examples and the hint with the jinja2 template. 

Maybe the templates are also an option for us instead of rewriting the task to use dicts. I'll give it a try!

Thanks
Tobias

**Comment by zerwes** [comment]
Hi Tobias
Glad if I could help in any way.
Just to give one more argument for the jinja2 templates:
We use our format for the network/vlan/rule/... definition in yaml format.
And from this "_single source of truth_" we derive the definitions in terms of "_separation of concern_" for the systems that are used to deploy the setup using ansible and jinja2 templates. So we create interface, vlan, alias and rule definitions for opnsense in the format expected by the role, vlan  definitions for the switch configuration playbook (dell, cisco, ...) etc.
I decided to go this way, even if one might argue that _*it is exactly what one should not do : it puts logic and complexity in a template*_, because this way I could:
 * have one single source for the definitions avoiding duplicated maintenance leading to errors etc.
 * be able to provide the expected format for the playbooks that deploy the setup (you can change the opnsense playbooks easily, one can even change the dellos or cisco playboocs, but you will put effort in a split off and completely detached personal solution, contrary to the open source idea)
 
At least this is the idea and the goal, we are on the right track, but still have some steps to go ...

Good luck with your effort
Greetings
Klaus

**Comment by zerwes** [comment]
added group example while working on #30 ...

**Comment by zerwes** [comment]
the test files `test/*.yml`) contain some example VARs too ...
